### PR TITLE
Push- i hope

### PR DESCRIPTION
**Pull request by bendnuts**

### CODE REVIEW

**Comment by bendnuts** [comment]
@Vitzual so ah, rejected or what

**Comment by Vitzual** [comment]
PR can't be accepted in current state. Please make sure PR's contain ONLY the file(s) you want to commit. Please also make sure you are up the latest version (you can merge main branch to yours)

Also if the asset is the same as the one shown on Discord, then no. Border outline is not consistent with the art style. If you aren't sure exactly how stuff should look, wait a bit longer until we have more assets available. Otherwise the actual copper part of the rock is spot on. Looks good. 

~ Ben

**Comment by Vitzual** [comment]
https://github.com/Vitzual/SpaceFactory/blob/main/Assets/Resources/Icons/Iron%20Ore.png

Example of what an ore might look like

**Comment by bendnuts** [comment]
> PR can't be accepted in current state. Please make sure PR's contain ONLY the file(s) you want to commit. Please also make sure you are up the latest version (you can merge main branch to yours)
> 
> Also if the asset is the same as the one shown on Discord, then no. Border outline is not consistent with the art style. If you aren't sure exactly how stuff should look, wait a bit longer until we have more assets available. Otherwise the actual copper part of the rock is spot on. Looks good.
> 
> ~ Ben

got it, thanks.

**Pull request closed without merging**
